##### Menu
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- github-card
- category
- links
- tagcloud
- rss
- weibo
- douban
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban



#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.png   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture
### Theme Color
theme_color:
    theme: '#a787d4'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: night

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: false      #enable mathjax if true

### Creative Commons License Support, see http://creativecommons.org/
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: by-nc-nd

#### Author information
author:
  intro_line1:  "Stay hungry, stay foolish"    ## your introduction on the bottom of the page
  intro_line2:  "Talk is cheap, show me the code."  ## the 2nd line
  weibo: 1680627603     ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier: c09974f5 ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina: 1680627603     ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  douban: 53279288    ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  zhihu: yulingtianxia     ## e.g. jark  for http://www.zhihu.com/people/jark
  email: yulingtianxia@gmail.com     ## e.g. imjark@gmail.com
  twitter: yulingtianxia   ## e.g. jarkwu for https://twitter.com/jarkwu
  github: yulingtianxia    ## e.g. wuchong for https://github.com/wuchong
  facebook: yulingtianxia  ## e.g. imjark for https://facebook.com/imjark
  linkedin: yulingtianxia  ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus: "106642427004837273341"   ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow: 2374982 ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  养小鱼的水塘: http://fish.yulingtianxia.com


#### Comment
duoshuo_shortname:    ## e.g. wuchong   your duoshuo short name.
disqus_shortname: yulingtianxia    ## e.g. wuchong   your disqus short name.
gentie_key:           ## your 163 gentie key, see https://gentie.163.com/
changyan_appid:       ## changyan app id, see http://changyan.kuaizhan.com/
changyan_appkey:      ## changyan app key, see http://changyan.kuaizhan.com/


#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: true
  id: UA-49704553-1       ## e.g. UA-46321946-2 your google analytics ID.
  site: auto     ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true
  sitecode: b5cb508df15ee6247a8c32c64eadb075 ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse:
  enable: true
  cx: 007120364111268919138:tex1pcfht90  ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site

tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
