##### Menu
menu:
  主页: /
  归档: /archives
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- links
- tagcloud
- rss
- weibo
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.png   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.

#### index post is expanding or not 
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More  
  
#### Author information
author:
  intro_line1:  "Stay hungry, stay foolish"    ## your introduction on the bottom of the page
  intro_line2:  "Talk is cheap, show me the code."  ## the 2nd line
  weibo: 1680627603
  weibo_verifier: c09974f5
  tsina: 1680627603
  douban: 53279288
  zhihu: yulingtianxia
  email: yulingtianxia@gmail.com
  twitter: yulingtianxia
  github: yulingtianxia
  facebook: yulingtianxia
  linkedin: yulingtianxia
  google_plus: "106642427004837273341"
  stackoverflow: 2374982
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  Spiral: http://spiral.yulingtianxia.com
  ColorAtom: http://coloratom.yulingtianxia.com
  畅游导航: http://changyou.yulingtianxia.com
  养小鱼的水塘: http://fish.yulingtianxia.com
  我的简历: http://resume.yulingtianxia.com 
#### Comment
duoshuo_shortname: yulingtianxia
disqus_shortname: yulingtianxia

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: true
  id: UA-49704553-1
  site: auto
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true
  sitecode: b5cb508df15ee6247a8c32c64eadb075
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse: 
  enable: true
  cx: 007120364111268919138:tex1pcfht90
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site:   ## your can change to your site instead of the default site
  
